inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines

